apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-k8s-iris-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-iris
  template:
    metadata:
      labels:
        app: k8s-iris
    spec:
      containers:
      - name: k8s-iris
        image: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>
