data:
  raw: data/Iris.csv
  preprocessed: data/preprocessed.csv
  random_state: 42
  test_size: 0.2

model:
  n_estimators: 100
  max_depths: 5
  random_state: 42

logging:
  level: INFO
  file: logs/train.log
